version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb_fei
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres_fei
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AH6033
      POSTGRES_DB: sistema_academico
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cassandra:
    image: cassandra:latest
    container_name: cassandra_fei
    restart: always
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: FEICluster
    volumes:
      - cassandra_data:/var/lib/cassandra

  app_python:
    build: ./src
    container_name: python_fei
    depends_on:
      - mongodb
      - postgres
      - cassandra
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app

volumes:
  mongo_data:
  pg_data:
  cassandra_data: